import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuroraBackground } from "@/components/ui/aurora-backgraound";

const inter = Inter();

export const metadata: Metadata = {
  title: "Rachdian | Personal Portofolio ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased `}>
        <AuroraBackground>{children}</AuroraBackground>
      </body>
    </html>
  );
}
// antialiased leading-6 h-[5000px]
